// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolHousing.Models;

namespace SchoolHousing.Migrations
{
    [DbContext(typeof(SchoolHousingContext))]
    [Migration("20191109230727_Initial Model")]
    partial class InitialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuickType.AffordableHouse", b =>
                {
                    b.Property<long>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("CommunityArea");

                    b.Property<string>("NameOfSchool");

                    b.Property<string>("PropertyName");

                    b.Property<string>("QualityOfFacilities");

                    b.Property<string>("StreetAddress");

                    b.Property<long>("ZipCode");

                    b.HasKey("SchoolId");

                    b.ToTable("AffordableHouse");
                });
#pragma warning restore 612, 618
        }
    }
}
